name: chargebee_dart
description: A wrapper for chargebee js
version: 0.0.2
homepage: https://lefty.io
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  js: ^0.6.1
  dart_browser_loader: ^0.0.3

dev_dependencies:
  test: ^0.12.0
  browser: ^0.10.0

web:
  compiler:
    debug: dartdevc