name: chargebee_dart
description: A wrapper for chargebee js
version: 0.0.3
homepage: https://lefty.io
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  js: ^0.6.1
  dart_browser_loader: ^0.0.3

dev_dependencies:
  test: ^1.3.0